funcao de silenciar
DanielChavesSimao/alarmobot pull request #23
Opened 2023-07-19 01:04 UTC by FabioPolinski

2023-07-19 01:25 UTC, DanielChavesSimao requested changes
.

2023-07-19 01:25 UTC, DanielChavesSimao commented on app/Http/Controllers/AlarmeController.php
> +        }
regra de negocio, eu moveria pro Model ou pra uma classe service e faria um getAttribute

2023-07-19 01:25 UTC, DanielChavesSimao commented on resources/views/alarmes/gerenciar.blade.php
> +                            </span>
o `$alarme->status` nao poderia retornar o status de disparado também?

2023-07-19 01:25 UTC, DanielChavesSimao commented on resources/views/alarmes/gerenciar.blade.php
> +                    @if($disparado)
a checagem de disparado ficaria dentro do model e nao precisaria dessa variavel extra. `$alarme->isDisparado()` retornaria `true` ou `false` e `$alarme->status` retorna um cast `Enum` chamado `AlarmeState`.

desse jeito daria pra fazer checagens usando `$alarme->status == AlarmeState::DISPARADO`

2023-07-19 01:25 UTC, DanielChavesSimao commented on resources/views/alarmes/gerenciar.blade.php
> +                                                <button onclick="openModal({{json_encode($ativacao->disparos->toArray())}})" style="color: rgb(107, 145, 223); text-decoration: underline;">
em vez de fazer esse javascript loco, poderia popular o modal com os dados direto no blade e deixar o js so pra mostrar ou esconder o modal

2023-07-21 00:50 UTC, danichurras approved these changes

2023-07-21 00:51 UTC, merged